enabled: true
name: hello
replicaCount: 1
host: demo-devcraft.continuousplatform.com
image:
  repository: hello
  tag: latest
  pullPolicy: Always
service:
  name: hello
  type: ClusterIP
  ports:
    - name: http
      port: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
sidecarIstio:
  enabled: true
