# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn clean install

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{secrets.DOCKER_REGISTRY_USERNAME}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        registry: realwavelab.azurecr.io
        repository: hello
        tags: latest,${{ github.sha }}
        tag_with_ref: false
        tag_with_sha: false

#     - name: AWS ECR
#       uses: kciter/aws-ecr-action@v1
#       with:
#         access_key_id: ${{secrets.AWS_ACCESS_KEY}}
#         secret_access_key: ${{secrets.AWS_SECRET_KEY}}
#         account_id: ${{secrets.AWS_ACCOUNT_ID}}
#         repo: hello
#         tags: latest,${{ github.sha }}
#         region: us-east-1
#         create_repo: true
